/**
 * Meta Graph API client.
 *
 * All Meta API access flows through this single class so the API version and
 * request/response shape are isolated in ONE place. Future Meta API changes
 * only require edits here — never in the CRM services or UI.
 *
 * The client is intentionally transport-agnostic: an optional `fetchImpl`
 * can be injected (used by tests to stub Meta without network calls).
 */

export const META_API_VERSION = "v19.0";
const GRAPH_BASE = `https://graph.facebook.com/${META_API_VERSION}`;

export interface MetaGraphError {
  message: string;
  type?: string;
  code?: number;
  error_subcode?: number;
}

export class MetaApiError extends Error {
  constructor(
    message: string,
    readonly code: number,
    readonly subcode?: number,
    readonly raw?: unknown
  ) {
    super(message);
    this.name = "MetaApiError";
  }
}

export interface MetaClientConfig {
  appId: string;
  appSecret: string;
  redirectUri: string;
  /** Injected in tests; defaults to global fetch. */
  fetchImpl?: typeof fetch;
}

export class MetaApiClient {
  readonly appId: string;
  readonly appSecret: string;
  readonly redirectUri: string;
  private readonly fetchImpl: typeof fetch;

  constructor(config: MetaClientConfig) {
    this.appId = config.appId;
    this.appSecret = config.appSecret;
    this.redirectUri = config.redirectUri;
    this.fetchImpl = config.fetchImpl ?? ((globalThis as { fetch?: typeof fetch }).fetch as typeof fetch);
    if (!this.fetchImpl) {
      throw new Error("No fetch implementation available for MetaApiClient");
    }
  }

  /** Builds the server-side OAuth URL (state must be generated by the caller). */
  buildAuthUrl(state: string, scope: string[]): string {
    const params = new URLSearchParams({
      client_id: this.appId,
      redirect_uri: this.redirectUri,
      state,
      scope: scope.join(","),
      response_type: "code",
    });
    return `https://www.facebook.com/${META_API_VERSION}/dialog/oauth?${params.toString()}`;
  }

  /** Exchanges an OAuth code for a user access token (long-lived exchange optional). */
  async exchangeCodeForToken(code: string): Promise<{
    accessToken: string;
    expiresIn: number;
    tokenType: string;
  }> {
    const params = new URLSearchParams({
      client_id: this.appId,
      client_secret: this.appSecret,
      redirect_uri: this.redirectUri,
      code,
    });
    const res = await this.fetchImpl(
      `${GRAPH_BASE}/oauth/access_token?${params.toString()}`
    );
    const json = await this.toJson(res);
    if (!json.access_token) {
      throw new MetaApiError("Meta did not return an access token", 0, undefined, json);
    }
    return {
      accessToken: String(json.access_token ?? ""),
      expiresIn: typeof json.expires_in === "number" ? json.expires_in : 0,
      tokenType: String(json.token_type ?? "bearer"),
    };
  }

  /** Exchanges a short-lived token for a long-lived (60 day) token. */
  async exchangeLongLivedToken(shortLived: string): Promise<{
    accessToken: string;
    expiresIn: number;
  }> {
    const params = new URLSearchParams({
      grant_type: "fb_exchange_token",
      client_id: this.appId,
      client_secret: this.appSecret,
      fb_exchange_token: shortLived,
    });
    const res = await this.fetchImpl(
      `${GRAPH_BASE}/oauth/access_token?${params.toString()}`
    );
    const json = await this.toJson(res);
    if (!json.access_token) {
      throw new MetaApiError("Long-lived token exchange failed", 0, undefined, json);
    }
    return {
      accessToken: String(json.access_token ?? ""),
      expiresIn: typeof json.expires_in === "number" ? json.expires_in : 0,
    };
  }

  /** Calls the Graph API with a bearer token. */
  async get<T = Record<string, unknown>>(
    path: string,
    token: string,
    query: Record<string, string> = {}
  ): Promise<T> {
    const qs = new URLSearchParams(query).toString();
    const url = `${GRAPH_BASE}/${path}${qs ? `?${qs}` : ""}`;
    const res = await this.fetchImpl(url, {
      headers: { Authorization: `Bearer ${token}` },
    });
    return (await this.toJson(res)) as T;
  }

  async post<T = Record<string, unknown>>(
    path: string,
    token: string,
    body: Record<string, string> = {}
  ): Promise<T> {
    const res = await this.fetchImpl(`${GRAPH_BASE}/${path}`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams(body).toString(),
    });
    return (await this.toJson(res)) as T;
  }

  private async toJson(res: Response): Promise<Record<string, unknown>> {
    const text = await res.text();
    let json: Record<string, unknown>;
    try {
      json = text ? JSON.parse(text) : {};
    } catch {
      throw new MetaApiError(`Meta returned non-JSON response (${res.status})`, res.status, undefined, text);
    }
    const error = json.error as MetaGraphError | undefined;
    if (error) {
      throw new MetaApiError(
        error.message ?? "Meta API error",
        error.code ?? res.status,
        error.error_subcode,
        json
      );
    }
    if (!res.ok) {
      throw new MetaApiError(`Meta API HTTP ${res.status}`, res.status, undefined, json);
    }
    return json;
  }
}

/** Resolves the configured Meta client, or null when Meta is not configured. */
export function buildMetaClient(fetchImpl?: typeof fetch): MetaApiClient | null {
  const appId = process.env.META_APP_ID;
  const appSecret = process.env.META_APP_SECRET;
  const redirectUri =
    process.env.META_REDIRECT_URI?.trim() ||
    (process.env.NODE_ENV === "production"
      ? "https://api.myclinic.myenum.in/api/meta/oauth/callback"
      : "http://localhost:3100/api/meta/oauth/callback");
  if (!appId || !appSecret) return null;
  return new MetaApiClient({ appId, appSecret, redirectUri, fetchImpl });
}
