import type { Prescription } from "@/components/prescriptions-table";
import type { Appointment } from "@/components/appointments-table";
import type { Bill, BillVisit } from "@/components/billing-table";
import { DEFAULT_CLINIC_NAME } from "@/lib/clinic-name-client";
import { formatTime } from "@/lib/format-time";

function escapeHtml(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "";
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const ONES = [
  "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
  "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
  "Seventeen", "Eighteen", "Nineteen",
];
const TENS = [
  "", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy",
  "Eighty", "Ninety",
];

function numberToWords(num: number): string {
  if (num === 0) return "";
  if (num < 20) return ONES[num];
  if (num < 100)
    return TENS[Math.floor(num / 10)] + (num % 10 ? " " + ONES[num % 10] : "");
  if (num < 1000)
    return (
      ONES[Math.floor(num / 100)] +
      " Hundred" +
      (num % 100 ? " " + numberToWords(num % 100) : "")
    );
  if (num < 100000)
    return (
      numberToWords(Math.floor(num / 1000)) +
      " Thousand" +
      (num % 1000 ? " " + numberToWords(num % 1000) : "")
    );
  if (num < 10000000)
    return (
      numberToWords(Math.floor(num / 100000)) +
      " Lakh" +
      (num % 100000 ? " " + numberToWords(num % 100000) : "")
    );
  return (
    numberToWords(Math.floor(num / 10000000)) +
    " Crore" +
    (num % 10000000 ? " " + numberToWords(num % 10000000) : "")
  );
}

function amountInWords(value: number): string {
  const n = Math.round((Number.isFinite(value) ? value : 0) * 100);
  const rupees = Math.floor(n / 100);
  const paise = n % 100;
  let words = rupees ? numberToWords(rupees) + " Rupees" : "";
  if (paise) words += (words ? " and " : "") + numberToWords(paise) + " Paise";
  return (words || "Zero") + " Only";
}

function formatDate(value: string | null | undefined) {
  if (!value) return "—";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
  }).format(parsed);
}

function money(value: number) {
  return "Rs. " + (value ?? 0).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function pageStyles() {
  return `
    body { font-family: Arial, sans-serif; color: #111; margin: 32px; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 16px; }
    .clinic { font-size: 20px; font-weight: bold; }
    .doc { font-size: 28px; font-weight: bold; color: #16a34a; }
    .row { display: flex; gap: 24px; flex-wrap: wrap; margin-bottom: 6px; font-size: 14px; }
    .row b { display: inline-block; min-width: 110px; }
    h3 { margin: 18px 0 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #f1f5f9; text-align: left; }
    .footer { margin-top: 32px; font-size: 13px; color: #555; }
  `;
}

function footer(clinicName: string = DEFAULT_CLINIC_NAME) {
  return `<div class="footer">Generated by ${clinicName} · ${formatDate(
    new Date().toISOString()
  )}</div>`;
}

export function prescriptionHtml(
  p: Prescription,
  clinicName: string = DEFAULT_CLINIC_NAME
) {
  const medicines = p.medicines.length
    ? p.medicines
        .map(
          (m, i) => `
            <tr>
              <td style="padding:8px;border:1px solid #ccc;">${i + 1}</td>
              <td style="padding:8px;border:1px solid #ccc;"><strong>${m.name || "—"}</strong></td>
              <td style="padding:8px;border:1px solid #ccc;">${m.frequency || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.duration || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.beforeAfterFood || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.specialInstructions || "—"}</td>
            </tr>`
        )
        .join("")
    : `<tr><td colspan="6" style="padding:8px;border:1px solid #ccc;text-align:center;">No medicines</td></tr>`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Prescription</title>
  <style>
    ${pageStyles()}
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="clinic">${clinicName}</div>
      <div style="font-size:12px;color:#555;">Doctor: ${p.doctorName || "—"}</div>
    </div>
    <div class="doc">Rx</div>
  </div>

  <div class="row"><b>Patient</b> ${p.patientName}</div>
  <div class="row"><b>Age / Gender</b> ${p.age ?? "—"} / ${p.gender ?? "—"}</div>
  <div class="row"><b>Phone</b> ${p.phone || "—"}</div>
  <div class="row"><b>Visit Date</b> ${formatDate(p.visitDate)}</div>
  <div class="row"><b>Diagnosis</b> ${p.diagnosis}</div>

  <h3>Medicines</h3>
  <table>
    <thead>
      <tr>
        <th style="padding:8px;border:1px solid #ccc;">#</th>
        <th style="padding:8px;border:1px solid #ccc;">Medicine</th>
        <th style="padding:8px;border:1px solid #ccc;">Frequency</th>
        <th style="padding:8px;border:1px solid #ccc;">Duration</th>
        <th style="padding:8px;border:1px solid #ccc;">Before / After Food</th>
        <th style="padding:8px;border:1px solid #ccc;">Special Instructions</th>
      </tr>
    </thead>
    <tbody>${medicines}</tbody>
  </table>

  ${p.symptoms ? `<h3>Symptoms / Notes</h3><div style="font-size:14px;">${p.symptoms}</div>` : ""}
  ${p.testsRecommended ? `<h3>Tests Recommended</h3><div style="font-size:14px;">${p.testsRecommended}</div>` : ""}
  <div class="row" style="margin-top:16px;"><b>Follow-up Date</b> ${formatDate(p.followUpDate)}</div>

  ${footer()}
</body>
</html>`;
}

export function appointmentHtml(
  a: Appointment,
  clinicName: string = DEFAULT_CLINIC_NAME
) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Appointment</title>
  <style>
    ${pageStyles()}
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="clinic">${clinicName}</div>
      <div style="font-size:12px;color:#555;">Doctor: ${a.doctorName || "—"}</div>
    </div>
    <div class="doc">Appointment</div>
  </div>

  <div class="row"><b>Patient</b> ${a.fullName}</div>
  <div class="row"><b>Mobile</b> ${a.mobile || "—"}</div>
  <div class="row"><b>Age / Gender</b> ${a.age ?? "—"} / ${a.gender ?? "—"}</div>
  <div class="row"><b>Department</b> ${a.department || "—"}</div>
  <div class="row"><b>Date</b> ${formatDate(a.date)}</div>
  <div class="row"><b>Time</b> ${formatTime(a.time)}</div>
  <div class="row"><b>Type</b> ${a.type === "video" ? "Video Consultation" : "In-person"}</div>
  <div class="row"><b>Status</b> ${a.status.replace("_", " ")}</div>
  ${a.reason ? `<div class="row"><b>Reason</b> ${a.reason}</div>` : ""}
  ${a.notes ? `<div class="row"><b>Notes</b> ${a.notes}</div>` : ""}

  ${footer()}
</body>
</html>`;
}

function billingStyles() {
  return `
    @page { size: A4; margin: 0; }
    html, body { margin: 0; padding: 0; background: #fff; }
    * { box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; color: #101828; font-size: 13px; line-height: 1.55; }
    .sheet {
      width: 210mm;
      min-height: 297mm;
      margin: 0 auto;
      padding: 10mm 12mm;
      border: 2px solid #0B2447;
      display: flex;
      flex-direction: column;
    }
    .clinic-header { display: flex; align-items: center; gap: 14px; padding-bottom: 12px; border-bottom: 2px solid #0B2447; margin-bottom: 16px; }
    .clinic-logo { width: 56px; height: 56px; object-fit: contain; flex-shrink: 0; }
    .clinic-name { font-size: 20px; font-weight: bold; color: #0B2447; letter-spacing: 0.5px; line-height: 1.3; }
    .clinic-line { font-size: 12px; color: #4B5563; margin-top: 3px; line-height: 1.5; }
    .doc-header { display: flex; justify-content: space-between; align-items: flex-start; gap: 20px; margin-bottom: 6px; }
    .invoice { text-align: right; font-size: 26px; font-weight: bold; color: #0B2447; line-height: 1.2; white-space: nowrap; }
    .invoice .inv-no { display: block; font-size: 13px; font-weight: bold; color: #1D4ED8; margin-top: 2px; }
    .invoice small { display: block; font-size: 12px; font-weight: normal; color: #555; margin-top: 6px; }
    .panels { flex: 1; display: flex; gap: 14px; min-width: 0; }
    .panel { flex: 1; background: #EEF3FA; border: 1px solid #DFE6F0; border-radius: 6px; padding: 11px 14px 12px; }
    .panel-title { display: inline-block; font-size: 11px; font-weight: bold; color: #0B2447; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #1D4ED8; padding-bottom: 3px; margin-bottom: 8px; }
    .patient-name { font-size: 14px; font-weight: bold; color: #101828; margin-bottom: 4px; }
    .patient-line { font-size: 12px; color: #4B5563; margin: 2px 0; line-height: 1.5; }
    .prow { display: flex; justify-content: space-between; gap: 12px; padding: 3px 0; }
    .prow span:first-child { color: #1D4ED8; font-weight: bold; font-size: 10px; text-transform: uppercase; letter-spacing: 0.4px; padding-top: 1px; }
    .prow span:last-child { color: #101828; font-weight: 600; text-align: right; }
    h3 { display: flex; align-items: center; gap: 10px; margin: 22px 0 10px; font-size: 13px; color: #0B2447; text-transform: uppercase; letter-spacing: 0.5px; }
    h3 .accent { width: 26px; height: 2px; background: #1D4ED8; flex-shrink: 0; }
    h3::after { content: ""; flex: 1; height: 1px; background: #C9D4E4; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #0B2447; color: #fff; text-align: left; padding: 8px 10px; border: 1px solid #0B2447; font-size: 11px; letter-spacing: 0.3px; }
    td { padding: 8px 10px; border: 1px solid #C9D4E4; vertical-align: top; line-height: 1.45; }
    tbody tr:nth-child(even) td { background: #EEF3FA; }
    .totals { width: 280px; margin-left: auto; margin-top: 18px; background: #EEF3FA; border: 1px solid #DFE6F0; border-radius: 6px; padding: 12px 14px 0; font-size: 14px; line-height: 1.5; }
    .totals div { display: flex; justify-content: space-between; padding: 4px 0; column-gap: 16px; }
    .totals .grand { margin: 8px -14px 0; padding: 11px 14px; background: #0B2447; color: #fff; border-radius: 0 0 6px 6px; font-size: 15px; font-weight: bold; }
    .words { margin-top: 14px; border: 1px solid #1D4ED8; border-radius: 5px; padding: 8px 14px; font-size: 13px; line-height: 1.6; }
    .words b { display: block; color: #1D4ED8; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 2px; }
    .footer { margin-top: auto; padding-top: 18px; }
    .footer .bar { background: #0B2447; color: #fff; border-radius: 4px; padding: 12px 16px; text-align: center; }
    .footer .bar b { display: block; font-size: 13px; margin-bottom: 2px; }
    .footer .bar span { font-size: 11px; color: #C7D2E0; }
    .paid { display: inline-block; padding: 3px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; color: #fff; background: #16A34A; }
    .pending { display: inline-block; padding: 3px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; color: #fff; background: #F59E0B; }
    .cancelled { display: inline-block; padding: 3px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; color: #fff; background: #EF4444; }
    .kv { display: grid; grid-template-columns: 150px 1fr; gap: 7px 12px; font-size: 13px; margin-top: 10px; line-height: 1.5; }
    .kv b { color: #1D4ED8; font-size: 11px; text-transform: uppercase; letter-spacing: 0.3px; }
  `;
}

function statusBadge(status: string) {
  const label = status.charAt(0).toUpperCase() + status.slice(1);
  return `<span class="${escapeHtml(status)}">${escapeHtml(label)}</span>`;
}

function clinicHeaderHtml(
  clinicName: string,
  visit?: BillVisit | null,
  logoUrl?: string
) {
  const clinic = visit?.clinic;
  const name = escapeHtml(clinic?.name?.trim() || clinicName);
  const lines: string[] = [];
  if (clinic?.address) lines.push(escapeHtml(clinic.address));
  const contacts: string[] = [];
  if (clinic?.phone) contacts.push(`Ph: ${escapeHtml(clinic.phone)}`);
  if (clinic?.email) contacts.push(escapeHtml(clinic.email));
  if (clinic?.website) contacts.push(escapeHtml(clinic.website));
  if (contacts.length) lines.push(contacts.join(" · "));
  return `
    <div class="clinic-header">
      ${logoUrl ? `<img class="clinic-logo" src="${escapeHtml(logoUrl)}" alt="" />` : ""}
      <div>
        <div class="clinic-name">${name}</div>
        ${lines.map((l) => `<div class="clinic-line">${l}</div>`).join("")}
      </div>
    </div>`;
}

function appointmentSectionHtml(appointment?: BillVisit["appointment"] | null) {
  if (!appointment) return "";
  const rows: [string, string][] = [
    ["Appointment ID", appointment.id ? escapeHtml(appointment.id.slice(-6).toUpperCase()) : "—"],
    ["Doctor", appointment.doctorName || "—"],
    ["Department", appointment.department || "—"],
    ["Date / Time", `${formatDate(appointment.date)}${appointment.time ? " · " + formatTime(appointment.time) : ""}`],
    ["Type", appointment.type === "video" ? "Video Consultation" : "In-person"],
    ["Status", appointment.status ? escapeHtml(appointment.status.replace("_", " ")) : "—"],
    ["Booking Source", appointment.bookingSource === "whatsapp_ai" ? "WhatsApp AI" : "Manual"],
  ];
  if (appointment.counter != null) rows.push(["Counter #", escapeHtml(String(appointment.counter))]);
  if (appointment.reason) rows.push(["Reason", escapeHtml(appointment.reason)]);
  if (appointment.notes) rows.push(["Notes", escapeHtml(appointment.notes)]);
  return `
    <h3>Appointment Details<span class="accent"></span></h3>
    <div class="kv">
      ${rows.map(([l, v]) => `<div><b>${escapeHtml(l)}</b></div><div>${v}</div>`).join("")}
    </div>`;
}

function prescriptionsSectionHtml(prescriptions?: BillVisit["prescriptions"]) {
  const list = Array.isArray(prescriptions) ? prescriptions.filter((p) => p) : [];
  if (!list.length) return "";
  return `
    <h3>Prescriptions &amp; Medicines<span class="accent"></span></h3>
    ${list
      .map((p) => {
        const medicines = Array.isArray(p.medicines)
          ? p.medicines.filter((m) => m?.name)
          : [];
        const meta: string[] = [];
        if (p.visitDate) meta.push(`Visit: ${formatDate(p.visitDate)}`);
        if (p.doctorName) meta.push(`Doctor: ${escapeHtml(p.doctorName)}`);
        if (p.followUpDate) meta.push(`Follow-up: ${formatDate(p.followUpDate)}`);
        const rows = medicines.length
          ? medicines
              .map(
                (m) => `
                  <tr>
                    <td><strong>${escapeHtml(m.name)}</strong></td>
                    <td>${escapeHtml(m.frequency)}</td>
                    <td>${escapeHtml(m.duration)}</td>
                    <td>${escapeHtml(m.beforeAfterFood)}</td>
                    <td>${escapeHtml(m.specialInstructions)}</td>
                  </tr>`
              )
              .join("")
          : `<tr><td colspan="5" style="text-align:center;">No medicines listed</td></tr>`;
        return `
          <p style="margin:6px 0;font-size:13px;"><strong>Diagnosis:</strong> ${escapeHtml(p.diagnosis || "—")}${meta.length ? ` <span style="color:#64748b;">· ${meta.join(" · ")}</span>` : ""}</p>
          ${p.symptoms ? `<p style="margin:4px 0;font-size:13px;"><strong>Symptoms / Notes:</strong> ${escapeHtml(p.symptoms)}</p>` : ""}
          ${p.testsRecommended ? `<p style="margin:4px 0 6px;font-size:13px;"><strong>Tests Recommended:</strong> ${escapeHtml(p.testsRecommended)}</p>` : ""}
          <table>
            <thead>
              <tr>
                <th>Medicine</th>
                <th>Frequency</th>
                <th>Duration</th>
                <th>Before / After Food</th>
                <th>Special Instructions</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>`;
      })
      .join("")}`;
}

function doctorsSectionHtml(doctors?: BillVisit["doctors"]) {
  const list = Array.isArray(doctors) ? doctors.filter((d) => d?.name) : [];
  if (!list.length) return "";
  return `
    <h3>Doctors<span class="accent"></span></h3>
    <table>
      <thead>
        <tr><th style="width:40px;">#</th><th>Doctor</th></tr>
      </thead>
      <tbody>
        ${list
          .map(
            (d, i) => `<tr><td>${i + 1}</td><td><strong>${escapeHtml(d.name)}</strong></td></tr>`
          )
          .join("")}
      </tbody>
    </table>`;
}

export function billingHtml(
  b: Bill,
  clinicName: string = DEFAULT_CLINIC_NAME,
  visit?: BillVisit | null,
  opts: { autoPrint?: boolean; logoUrl?: string } = {}
) {
  const rows = b.items.length
    ? b.items
        .map(
          (item, i) => `
            <tr>
              <td style="text-align:center;">${i + 1}</td>
              <td><strong>${escapeHtml(item.name || "—")}</strong></td>
              <td style="text-align:center;">${item.qty}</td>
              <td style="text-align:right;">${money(item.price)}</td>
              <td style="text-align:right;">${money(item.amount)}</td>
            </tr>`
        )
        .join("")
    : `<tr><td colspan="5" style="text-align:center;">No items</td></tr>`;

  const patient = visit?.patient;
  const ageGender = [patient?.age ? `${patient.age} yrs` : "", patient?.gender ? escapeHtml(String(patient.gender)) : ""]
    .filter(Boolean)
    .join(" / ");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Invoice ${escapeHtml(b.billNumber)}</title>
  <style>
    ${billingStyles()}
  </style>
</head>
<body>
  <div class="sheet">
    ${clinicHeaderHtml(clinicName, visit, opts.logoUrl)}

    <div class="doc-header">
      <div class="panels">
        <div class="panel">
          <div class="panel-title">Billed To</div>
          <div class="patient-name">${escapeHtml(b.patientName)}</div>
          ${b.patientPhone ? `<div class="patient-line">${escapeHtml(b.patientPhone)}</div>` : ""}
          ${ageGender ? `<div class="patient-line">${escapeHtml(ageGender)}</div>` : ""}
          ${visit?.patient?.email ? `<div class="patient-line">${escapeHtml(visit.patient.email)}</div>` : ""}
        </div>
        <div class="panel">
          <div class="panel-title">Invoice &amp; Payment</div>
          <div class="prow"><span>Date</span><span>${formatDate(b.date)}</span></div>
          <div class="prow"><span>Invoice No.</span><span>${escapeHtml(b.billNumber)}</span></div>
          <div class="prow"><span>Doctor</span><span>${escapeHtml(b.doctorName || "—")}</span></div>
          <div class="prow"><span>Payment</span><span>${escapeHtml(b.paymentMethod || "—")}</span></div>
        </div>
      </div>
      <div class="invoice">
        Invoice
        <span class="inv-no">${escapeHtml(b.billNumber)}</span>
        <small>${statusBadge(b.status)}</small>
      </div>
    </div>

    ${appointmentSectionHtml(visit?.appointment ?? null)}
    ${prescriptionsSectionHtml(visit?.prescriptions)}
    ${doctorsSectionHtml(visit?.doctors)}

    <h3>Bill Items<span class="accent"></span></h3>
    <table>
      <thead>
        <tr>
          <th style="width:36px;">#</th>
          <th>Item / Service</th>
          <th style="width:52px;">Qty</th>
          <th style="width:100px;">Price</th>
          <th style="width:110px;">Amount</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>

    <div class="totals">
      <div><span>Subtotal</span><span>${money(b.subtotal)}</span></div>
      ${b.discount ? `<div><span>Discount</span><span>−${money(b.discount)}</span></div>` : ""}
      ${b.tax ? `<div><span>Tax (${b.taxRate}%)</span><span>${money(b.tax)}</span></div>` : ""}
      <div class="grand"><span>GRAND TOTAL</span><span>${money(b.total)}</span></div>
    </div>

    <div class="words"><b>Amount in Words</b>${escapeHtml(amountInWords(b.total))}</div>

    ${b.notes ? `<h3>Notes<span class="accent"></span></h3><div style="font-size:13px;">${escapeHtml(b.notes)}</div>` : ""}

    <div class="footer">
      <div class="bar">
        <b>Thank you for visiting ${escapeHtml(clinicName)}</b>
        <span>${escapeHtml(clinicName)} · Generated on ${formatDate(new Date().toISOString())}</span>
      </div>
    </div>
  </div>
  ${opts.autoPrint ? `<script>window.onload = function () { window.print(); };</script>` : ""}
</body>
</html>`;
}
