import type { Prescription } from "@/components/prescriptions-table";
import type { Appointment } from "@/components/appointments-table";
import type { Bill } from "@/components/billing-table";

function formatDate(value: string | null | undefined) {
  if (!value) return "—";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "2-digit",
    year: "numeric",
  }).format(parsed);
}

function money(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
  }).format(value ?? 0);
}

function pageStyles() {
  return `
    body { font-family: Arial, sans-serif; color: #111; margin: 32px; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #111; padding-bottom: 12px; margin-bottom: 16px; }
    .clinic { font-size: 20px; font-weight: bold; }
    .doc { font-size: 28px; font-weight: bold; color: #16a34a; }
    .row { display: flex; gap: 24px; flex-wrap: wrap; margin-bottom: 6px; font-size: 14px; }
    .row b { display: inline-block; min-width: 110px; }
    h3 { margin: 18px 0 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #f1f5f9; text-align: left; }
    .footer { margin-top: 32px; font-size: 13px; color: #555; }
  `;
}

function footer() {
  return `<div class="footer">Generated by My Clinic · ${formatDate(
    new Date().toISOString()
  )}</div>`;
}

export function prescriptionHtml(p: Prescription) {
  const medicines = p.medicines.length
    ? p.medicines
        .map(
          (m, i) => `
            <tr>
              <td style="padding:8px;border:1px solid #ccc;">${i + 1}</td>
              <td style="padding:8px;border:1px solid #ccc;"><strong>${m.name || "—"}</strong></td>
              <td style="padding:8px;border:1px solid #ccc;">${m.frequency || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.duration || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.beforeAfterFood || "—"}</td>
              <td style="padding:8px;border:1px solid #ccc;">${m.specialInstructions || "—"}</td>
            </tr>`
        )
        .join("")
    : `<tr><td colspan="6" style="padding:8px;border:1px solid #ccc;text-align:center;">No medicines</td></tr>`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Prescription</title>
  <style>
    ${pageStyles()}
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="clinic">My Clinic</div>
      <div style="font-size:12px;color:#555;">Doctor: ${p.doctorName || "—"}</div>
    </div>
    <div class="doc">Rx</div>
  </div>

  <div class="row"><b>Patient</b> ${p.patientName}</div>
  <div class="row"><b>Age / Gender</b> ${p.age ?? "—"} / ${p.gender ?? "—"}</div>
  <div class="row"><b>Phone</b> ${p.phone || "—"}</div>
  <div class="row"><b>Visit Date</b> ${formatDate(p.visitDate)}</div>
  <div class="row"><b>Diagnosis</b> ${p.diagnosis}</div>

  <h3>Medicines</h3>
  <table>
    <thead>
      <tr>
        <th style="padding:8px;border:1px solid #ccc;">#</th>
        <th style="padding:8px;border:1px solid #ccc;">Medicine</th>
        <th style="padding:8px;border:1px solid #ccc;">Frequency</th>
        <th style="padding:8px;border:1px solid #ccc;">Duration</th>
        <th style="padding:8px;border:1px solid #ccc;">Before / After Food</th>
        <th style="padding:8px;border:1px solid #ccc;">Special Instructions</th>
      </tr>
    </thead>
    <tbody>${medicines}</tbody>
  </table>

  ${p.symptoms ? `<h3>Symptoms / Notes</h3><div style="font-size:14px;">${p.symptoms}</div>` : ""}
  ${p.testsRecommended ? `<h3>Tests Recommended</h3><div style="font-size:14px;">${p.testsRecommended}</div>` : ""}
  <div class="row" style="margin-top:16px;"><b>Follow-up Date</b> ${formatDate(p.followUpDate)}</div>

  ${footer()}
</body>
</html>`;
}

export function appointmentHtml(a: Appointment) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Appointment</title>
  <style>
    ${pageStyles()}
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="clinic">My Clinic</div>
      <div style="font-size:12px;color:#555;">Doctor: ${a.doctorName || "—"}</div>
    </div>
    <div class="doc">Appointment</div>
  </div>

  <div class="row"><b>Patient</b> ${a.fullName}</div>
  <div class="row"><b>Mobile</b> ${a.mobile || "—"}</div>
  <div class="row"><b>Age / Gender</b> ${a.age ?? "—"} / ${a.gender ?? "—"}</div>
  <div class="row"><b>Department</b> ${a.department || "—"}</div>
  <div class="row"><b>Date</b> ${formatDate(a.date)}</div>
  <div class="row"><b>Time</b> ${a.time || "—"}</div>
  <div class="row"><b>Type</b> ${a.type === "video" ? "Video Consultation" : "In-person"}</div>
  <div class="row"><b>Status</b> ${a.status.replace("_", " ")}</div>
  ${a.reason ? `<div class="row"><b>Reason</b> ${a.reason}</div>` : ""}
  ${a.notes ? `<div class="row"><b>Notes</b> ${a.notes}</div>` : ""}

  ${footer()}
</body>
</html>`;
}

export function billingHtml(b: Bill) {
  const rows = b.items.length
    ? b.items
        .map(
          (item, i) => `
            <tr>
              <td style="padding:8px;border:1px solid #ccc;">${i + 1}</td>
              <td style="padding:8px;border:1px solid #ccc;"><strong>${item.name || "—"}</strong></td>
              <td style="padding:8px;border:1px solid #ccc;">${item.qty}</td>
              <td style="padding:8px;border:1px solid #ccc;">${money(item.price)}</td>
              <td style="padding:8px;border:1px solid #ccc;">${money(item.amount)}</td>
            </tr>`
        )
        .join("")
    : `<tr><td colspan="5" style="padding:8px;border:1px solid #ccc;text-align:center;">No items</td></tr>`;

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Invoice ${b.billNumber}</title>
  <style>
    ${pageStyles()}
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="clinic">My Clinic</div>
      <div style="font-size:12px;color:#555;">Doctor: ${b.doctorName || "—"}</div>
    </div>
    <div class="doc">Invoice</div>
  </div>

  <div class="row"><b>Invoice No.</b> ${b.billNumber}</div>
  <div class="row"><b>Patient</b> ${b.patientName}</div>
  <div class="row"><b>Phone</b> ${b.patientPhone || "—"}</div>
  <div class="row"><b>Date</b> ${formatDate(b.date)}</div>
  <div class="row"><b>Payment</b> ${b.paymentMethod || "—"}</div>
  <div class="row"><b>Status</b> ${b.status}</div>

  <h3>Bill Items</h3>
  <table>
    <thead>
      <tr>
        <th style="padding:8px;border:1px solid #ccc;">#</th>
        <th style="padding:8px;border:1px solid #ccc;">Item</th>
        <th style="padding:8px;border:1px solid #ccc;">Qty</th>
        <th style="padding:8px;border:1px solid #ccc;">Price</th>
        <th style="padding:8px;border:1px solid #ccc;">Amount</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="row" style="margin-top:16px;"><b>Subtotal</b> ${money(b.subtotal)}</div>
  ${b.discount ? `<div class="row"><b>Discount</b> -${money(b.discount)}</div>` : ""}
  ${b.tax ? `<div class="row"><b>Tax (${b.taxRate}%)</b> ${money(b.tax)}</div>` : ""}
  <div class="row"><b style="min-width:110px;font-size:16px;">Total</b><strong style="font-size:16px;">${money(b.total)}</strong></div>
  ${b.notes ? `<div class="row"><b>Notes</b> ${b.notes}</div>` : ""}

  ${footer()}
</body>
</html>`;
}
